

services:
  tpadds2024:
    build: .
    ports:
      - "9001:9001"
    environment:
      DB_URL: jdbc:mysql://tpa_db:3306/dds_grupo9?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      tpa_db:
        condition: service_healthy
  tpa_db:
    image: mysql:8.0.17
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: dds_grupo9
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10